### ISSUE TITLE
Feature Request: Can cross 1 block hight

### ISSUE THREAD

**Issue by FirdausCraft10** [ZsoltMolnarrr/Rolling#20] opened 2023-02-22 07:21 UTC
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES/NO

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZsoltMolnarrr** [comment] 2023-02-22 09:22
Duplicate of #18

**Closed as completed by ZsoltMolnarrr** 2023-02-22 09:22 UTC
