### ISSUE TITLE
1.20.1 Crashes When Loading A World

### ISSUE THREAD

**Issue by IAmInYourWall** [ZsoltMolnarrr/Rolling#24] opened 2023-07-09 00:42 UTC
Any time I try to load a world with this mod in the mods folder, it gets to "Loading Textures" and then crashes and gives the crash message "Error: lava.lang.IllegalArgumentException: Can't find attribute combatroll:count" with the exit code 255. I am using Forge 1.20.1 with the latest version of the mod that is available on Forge 1.20.1.

**Comment by GitUser14975** [comment] 2023-07-09 20:44
Had the same issue.
Here's my crash log: https://gist.github.com/TenKotowsky/b78f1b7894e3656357b609ebb9f5a8ee

**Comment by ZsoltMolnarrr** [comment] 2023-07-15 22:09
Thank you for reporting. I'll investigate.

**Comment by ZsoltMolnarrr** [comment] 2023-07-16 08:45
What is the in-game usecase to reproduce this crash?

**Comment by GitUser14975** [comment] 2023-07-17 14:41
> What is the in-game usecase to reproduce this crash?

For me, if I remember correctly, it crashed at start when I tried to join the world. I didn't even start playing, it just crashed instantly as soon as the world loaded

**Comment by ZsoltMolnarrr** [comment] 2023-07-17 19:15
Launching the game and entering the world does not produce a crash for me, this is most likely a conflict with some other mod.
In order to fix the issue, I need to know which specific mod causes this.

**Comment by AngelTechnic** [comment] 2023-07-30 00:17
i actually had the same issue, but i'm running the 1.19 version of the mod on quilt. 

here's my crash report (and it comes with a modlist) https://pastebin.com/bphrNhZr

**Comment by Talan67** [comment] 2023-07-31 18:12
Ok I think I have found the issue, it seems to be Pufferfish's Skills and based on the previous reply it seems to be affecting fabric as well. I think this might be something to do with the custom attributes added with pufferfish skills that might be casuing the game to abrupptly crash as they are immediatley loaded up on world join/enter.

Heres logs, keep in mind I got a pretty big mod list:

[latest.log](https://github.com/ZsoltMolnarrr/CombatRoll/files/12217916/latest.log)
[crash-2023-07-31_18.52.33-client.txt](https://github.com/ZsoltMolnarrr/CombatRoll/files/12217918/crash-2023-07-31_18.52.33-client.txt)


Will also report this issue on Pufferfishe's Skills Github

**Comment by tablenitro** [comment] 2023-08-16 10:02
Anyone who wants something similar to "pufferfish's skills" use this mod instead "Passive Skill Tree"
https://www.curseforge.com/minecraft/mc-mods/passive-skill-tree

**Comment by ZsoltMolnarrr** [comment] 2023-08-24 14:48
It looks like the third party mod in question is referencing a combat roll attribute at an incorrect time (before its registration).
This cannot be fixed by Combat Roll.

Closing the issue due to being non-actionable.
Feel free to reopen in when a hint of (specific) technical shortcoming of Combat Roll arises.

**Closed as completed by ZsoltMolnarrr** 2023-08-24 14:48 UTC
Labels: help wanted
